# Generated by Django 5.2.17 on 2026-09-02 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.category', verbose_name='카테고리 연결'),
        ),
    ]
