# Generated by Django 5.2.17 on 2026-09-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_link_existing_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
