# Generated by Django 5.2.17 on 2026-09-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category_ref',
            new_name='category',
        ),
    ]
