# Generated by Django 5.2.17 on 2026-09-14 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_update_category_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True, verbose_name='예산 월')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='월 예산')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date', 'id'], name='expense_date_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='budget_amount_positive'),
        ),
    ]
